### 3.1.1. Carga de Datos

In [2]:
# Importar paquetes
import pandas as pd
import numpy as np

In [3]:
# Carga
data_ori = pd.read_csv('datos/churn/DS_Churn_Banca_ori.csv')

In [44]:
import random
list_ale = random.sample(range(0,len(data_ori)),k = 10000)
list_ale.sort()
list_ale

[20,
 22,
 27,
 28,
 31,
 43,
 46,
 60,
 62,
 70,
 82,
 87,
 92,
 102,
 117,
 143,
 145,
 146,
 157,
 160,
 169,
 173,
 199,
 202,
 212,
 273,
 277,
 285,
 287,
 289,
 291,
 299,
 301,
 309,
 319,
 327,
 339,
 350,
 357,
 366,
 370,
 373,
 374,
 375,
 383,
 386,
 390,
 395,
 396,
 398,
 399,
 400,
 402,
 403,
 415,
 441,
 447,
 450,
 451,
 452,
 455,
 457,
 463,
 465,
 475,
 478,
 485,
 507,
 515,
 526,
 531,
 532,
 535,
 538,
 540,
 552,
 553,
 561,
 562,
 569,
 571,
 583,
 595,
 605,
 611,
 612,
 627,
 634,
 642,
 649,
 650,
 655,
 664,
 667,
 669,
 684,
 685,
 704,
 706,
 712,
 724,
 729,
 730,
 731,
 745,
 747,
 749,
 756,
 759,
 768,
 787,
 789,
 790,
 798,
 818,
 820,
 822,
 832,
 837,
 842,
 843,
 848,
 849,
 858,
 873,
 881,
 886,
 897,
 905,
 906,
 917,
 942,
 944,
 959,
 966,
 969,
 984,
 990,
 991,
 992,
 998,
 1000,
 1009,
 1013,
 1014,
 1018,
 1021,
 1026,
 1044,
 1046,
 1047,
 1052,
 1059,
 1060,
 1063,
 1067,
 1072,
 1082,
 1086,
 1092,
 1109,
 1112,
 1128,
 1147,
 1149,
 1173,
 1187,
 1191,
 1197,
 1198,
 1200,
 1223,
 1229,
 1237,
 1244,
 1245,
 1248,
 1249,
 1255,
 1256,
 1265,
 1268,
 1274,
 1286,
 1291,
 1300,
 1306,
 1308,
 1318,
 1320,
 1321,
 1323,
 1328,
 1335,
 1347,
 1354,
 1355,
 1357,
 1368,
 1375,
 1377,
 1387,
 1407,
 1427,
 1431,
 1451,
 1460,
 1463,
 1464,
 1465,
 1476,
 1480,
 1489,
 1491,
 1495,
 1496,
 1497,
 1502,
 1516,
 1518,
 1533,
 1535,
 1536,
 1546,
 1551,
 1563,
 1567,
 1576,
 1580,
 1596,
 1601,
 1602,
 1603,
 1622,
 1624,
 1632,
 1640,
 1652,
 1661,
 1664,
 1665,
 1672,
 1681,
 1691,
 1696,
 1708,
 1714,
 1724,
 1726,
 1728,
 1749,
 1765,
 1769,
 1775,
 1782,
 1787,
 1788,
 1789,
 1792,
 1799,
 1802,
 1807,
 1812,
 1813,
 1817,
 1822,
 1835,
 1854,
 1858,
 1861,
 1868,
 1869,
 1870,
 1871,
 1875,
 1880,
 1882,
 1884,
 1897,
 1898,
 1901,
 1906,
 1932,
 1945,
 1956,
 1958,
 1959,
 1961,
 1967,
 1978,
 1980,
 1981,
 1984,
 1987,
 1988,
 1997,
 2011,
 2014,
 2018,
 2019,
 2024,
 2026,
 2027,
 2029,
 2030,
 2031,
 2037,
 2041,
 2048,
 2126,
 2155,
 2157,
 2171,
 2182,
 2184,
 2196,
 2204,
 2206,
 2213,
 2214,
 2222,
 2227,
 2231,
 2232,
 2254,
 2266,
 2270,
 2273,
 2289,
 2294,
 2306,
 2310,
 2322,
 2324,
 2328,
 2337,
 2338,
 2341,
 2342,
 2357,
 2358,
 2367,
 2368,
 2369,
 2374,
 2380,
 2386,
 2394,
 2397,
 2399,
 2405,
 2415,
 2424,
 2430,
 2445,
 2471,
 2487,
 2493,
 2494,
 2495,
 2496,
 2509,
 2512,
 2552,
 2561,
 2574,
 2578,
 2582,
 2584,
 2588,
 2589,
 2632,
 2637,
 2641,
 2653,
 2657,
 2669,
 2670,
 2676,
 2683,
 2684,
 2687,
 2702,
 2709,
 2725,
 2730,
 2731,
 2751,
 2754,
 2759,
 2765,
 2782,
 2783,
 2800,
 2820,
 2821,
 2824,
 2829,
 2842,
 2847,
 2848,
 2854,
 2868,
 2872,
 2879,
 2883,
 2892,
 2893,
 2896,
 2901,
 2906,
 2909,
 2910,
 2915,
 2918,
 2924,
 2928,
 2936,
 2939,
 2941,
 2948,
 2951,
 2973,
 2983,
 2989,
 2992,
 2998,
 3018,
 3024,
 3031,
 3039,
 3040,
 3045,
 3058,
 3066,
 3075,
 3078,
 3088,
 3093,
 3113,
 3122,
 3128,
 3132,
 3136,
 3138,
 3145,
 3152,
 3159,
 3160,
 3164,
 3172,
 3175,
 3184,
 3204,
 3207,
 3208,
 3214,
 3227,
 3229,
 3244,
 3253,
 3261,
 3264,
 3280,
 3285,
 3300,
 3308,
 3311,
 3315,
 3320,
 3323,
 3349,
 3353,
 3369,
 3388,
 3390,
 3391,
 3402,
 3413,
 3414,
 3418,
 3427,
 3429,
 3432,
 3438,
 3442,
 3443,
 3464,
 3471,
 3475,
 3481,
 3482,
 3487,
 3492,
 3493,
 3495,
 3501,
 3510,
 3515,
 3518,
 3520,
 3540,
 3541,
 3546,
 3548,
 3563,
 3565,
 3573,
 3589,
 3593,
 3595,
 3598,
 3604,
 3607,
 3608,
 3614,
 3616,
 3617,
 3626,
 3635,
 3637,
 3643,
 3646,
 3649,
 3665,
 3668,
 3669,
 3675,
 3684,
 3690,
 3699,
 3701,
 3704,
 3709,
 3717,
 3720,
 3725,
 3734,
 3743,
 3748,
 3754,
 3755,
 3762,
 3765,
 3766,
 3767,
 3769,
 3775,
 3776,
 3780,
 3787,
 3797,
 3798,
 3823,
 3838,
 3842,
 3854,
 3857,
 3866,
 3867,
 3877,
 3888,
 3894,
 3898,
 3908,
 3916,
 3917,
 3918,
 3942,
 3943,
 3948,
 3949,
 3956,
 3958,
 3959,
 3967,
 3974,
 3986,
 3999,
 4003,
 4005,
 4008,
 4013,
 4016,
 4044,
 4061,
 4071,
 4083,
 4085,
 4089,
 4096,
 4107,
 4115,
 4128,
 4130,
 4141,
 4148,
 4149,
 4168,
 4191,
 4193,
 4198,
 4199,
 4200,
 4207,
 4222,
 4226,
 4231,
 4234,
 4256,
 4257,
 4260,
 4272,
 4280,
 4302,
 4304,
 4308,
 4313,
 4338,
 4339,
 4351,
 4356,
 4360,
 4368,
 4369,
 4370,
 4373,
 4379,
 4384,
 4417,
 4419,
 4422,
 4424,
 4435,
 4440,
 4443,
 4447,
 4456,
 4459,
 4460,
 4473,
 4474,
 4477,
 4484,
 4497,
 4501,
 4511,
 4512,
 4521,
 4526,
 4534,
 4540,
 4543,
 4567,
 4569,
 4573,
 4585,
 4592,
 4614,
 4624,
 4625,
 4630,
 4634,
 4641,
 4645,
 4656,
 4664,
 4668,
 4671,
 4675,
 4676,
 4680,
 4682,
 4683,
 4684,
 4702,
 4704,
 4708,
 4709,
 4710,
 4718,
 4726,
 4740,
 4741,
 4746,
 4752,
 4753,
 4754,
 4769,
 4771,
 4773,
 4778,
 4779,
 4787,
 4800,
 4802,
 4804,
 4805,
 4816,
 4822,
 4823,
 4844,
 4847,
 4851,
 4852,
 4853,
 4864,
 4917,
 4924,
 4925,
 4946,
 4971,
 4975,
 4978,
 4986,
 4997,
 5012,
 5034,
 5047,
 5060,
 5062,
 5065,
 5067,
 5072,
 5075,
 5078,
 5081,
 5087,
 5089,
 5099,
 5104,
 5108,
 5112,
 5113,
 5114,
 5123,
 5126,
 5130,
 5132,
 5138,
 5154,
 5156,
 5161,
 5164,
 5165,
 5166,
 5169,
 5171,
 5172,
 5199,
 5202,
 5209,
 5216,
 5220,
 5221,
 5222,
 5224,
 5227,
 5229,
 5234,
 5237,
 5238,
 5240,
 5245,
 5263,
 5291,
 5297,
 5298,
 5299,
 5301,
 5311,
 5313,
 5314,
 5316,
 5321,
 5339,
 5346,
 5351,
 5367,
 5368,
 5370,
 5372,
 5375,
 5377,
 5380,
 5397,
 5400,
 5409,
 5413,
 5416,
 5421,
 5448,
 5452,
 5460,
 5466,
 5469,
 5480,
 5481,
 5483,
 5484,
 5486,
 5496,
 5508,
 5510,
 5526,
 5529,
 5535,
 5552,
 5562,
 5568,
 5574,
 5588,
 5591,
 5599,
 5603,
 5619,
 5627,
 5635,
 5637,
 5642,
 5647,
 5648,
 5661,
 5671,
 5676,
 5678,
 5679,
 5684,
 5688,
 5691,
 5695,
 5696,
 5699,
 5704,
 5715,
 5720,
 5721,
 5722,
 5739,
 5742,
 5746,
 5751,
 5753,
 5756,
 5772,
 5774,
 5776,
 5786,
 5788,
 5789,
 5793,
 5795,
 5801,
 5813,
 5824,
 5837,
 5838,
 5844,
 5852,
 5861,
 5888,
 5890,
 5912,
 5914,
 5922,
 5925,
 5926,
 5928,
 5935,
 5936,
 5944,
 5945,
 5946,
 5947,
 5965,
 5971,
 5972,
 5977,
 5982,
 5987,
 5988,
 6000,
 6001,
 6010,
 6016,
 6024,
 6033,
 6042,
 6045,
 6048,
 6051,
 6052,
 6058,
 6064,
 6070,
 6085,
 6089,
 6092,
 6093,
 6103,
 6113,
 6125,
 6129,
 6131,
 6135,
 6145,
 6153,
 6165,
 6166,
 6169,
 6178,
 6191,
 6200,
 6205,
 6206,
 6214,
 6226,
 6227,
 6251,
 6255,
 6263,
 6264,
 6273,
 6276,
 6278,
 6292,
 6298,
 6304,
 6305,
 6312,
 6320,
 6322,
 6344,
 6346,
 6357,
 6363,
 6364,
 6365,
 6366,
 6385,
 6388,
 6395,
 6408,
 6409,
 6410,
 6416,
 6426,
 6430,
 6462,
 6466,
 6490,
 6491,
 6501,
 6507,
 6516,
 6520,
 6524,
 6537,
 6542,
 6548,
 6555,
 6558,
 6562,
 6564,
 6565,
 6566,
 6569,
 6574,
 6577,
 6579,
 6585,
 6592,
 6593,
 6594,
 6596,
 6609,
 6612,
 6615,
 6619,
 6623,
 6628,
 6629,
 6634,
 6639,
 6647,
 6660,
 6675,
 6682,
 6687,
 6699,
 6715,
 6730,
 6736,
 6749,
 6761,
 6764,
 6770,
 6771,
 6787,
 6792,
 ...]

In [45]:
# TABLA 1:
VARS_T1 = ['ID_CORRELATIVO',
'CODMES',
'ATTRITION',
'FLG_BANCARIZADO',
'RANG_INGRESO',
'FLAG_LIMA_PROVINCIA',
'EDAD',
'ANTIGUEDAD',
'RANG_SDO_PASIVO_MENOS0',
'FLG_NOMINA',
'RANG_NRO_PRODUCTOS_MENOS0',
'SDO_ACTIVO_MENOS0',
'FLG_SEGURO_MENOS0',
'NRO_ACCES_CANAL1_MENOS0',
'NRO_ACCES_CANAL2_MENOS0',
'NRO_ACCES_CANAL3_MENOS0',
'NRO_ENTID_SSFF_MENOS0',
'FLG_SDO_OTSSFF_MENOS0']
TABLA1 = data_ori.loc[list_ale,VARS_T1]
TABLA1.head()

,ID_CORRELATIVO,CODMES,ATTRITION,FLG_BANCARIZADO,RANG_INGRESO,FLAG_LIMA_PROVINCIA,EDAD,ANTIGUEDAD,RANG_SDO_PASIVO_MENOS0,FLG_NOMINA,RANG_NRO_PRODUCTOS_MENOS0,SDO_ACTIVO_MENOS0,FLG_SEGURO_MENOS0,NRO_ACCES_CANAL1_MENOS0,NRO_ACCES_CANAL2_MENOS0,NRO_ACCES_CANAL3_MENOS0,NRO_ENTID_SSFF_MENOS0,FLG_SDO_OTSSFF_MENOS0
20,11752,201208,0,1,Rang_ingreso_01,Provincia,36.0,0.0,Cero,0,Rango_01,0,0,0,0,0,2,1
22,98898,201208,0,0,Rang_ingreso_01,Lima,23.0,0.0,Rango_SDO_02,1,Rango_02,0,0,0,0,7,0,0
27,82206,201208,0,1,Rang_ingreso_02,Provincia,24.0,0.0,Rango_SDO_01,1,Rango_02,0,0,0,0,16,1,1
28,50435,201208,1,1,Rang_ingreso_01,Provincia,30.0,NaN,Cero,0,Rango_02,0,1,0,0,0,5,1
31,79004,201208,0,0,NaN,Provincia,30.0,0.0,Rango_SDO_10,0,Rango_02,0,0,0,0,1,0,0

In [46]:
TABLA1.to_csv('datos/churn/DS_Churn_Banca_CLIENTE.csv',index=False)

In [47]:
# TABLA 2:
VARS_T2 = ['ID_CORRELATIVO',
'CODMES',
'SDO_ACTIVO_MENOS0',
'SDO_ACTIVO_MENOS1',
'SDO_ACTIVO_MENOS2',
'SDO_ACTIVO_MENOS3',
'SDO_ACTIVO_MENOS4',
'SDO_ACTIVO_MENOS5',
'FLG_SEGURO_MENOS0',
'FLG_SEGURO_MENOS1',
'FLG_SEGURO_MENOS2',
'FLG_SEGURO_MENOS3',
'FLG_SEGURO_MENOS4',
'FLG_SEGURO_MENOS5',
'NRO_ACCES_CANAL1_MENOS0',
'NRO_ACCES_CANAL1_MENOS1',
'NRO_ACCES_CANAL1_MENOS2',
'NRO_ACCES_CANAL1_MENOS3',
'NRO_ACCES_CANAL1_MENOS4',
'NRO_ACCES_CANAL1_MENOS5',
'NRO_ACCES_CANAL2_MENOS0',
'NRO_ACCES_CANAL2_MENOS1',
'NRO_ACCES_CANAL2_MENOS2',
'NRO_ACCES_CANAL2_MENOS3',
'NRO_ACCES_CANAL2_MENOS4',
'NRO_ACCES_CANAL2_MENOS5',
'NRO_ACCES_CANAL3_MENOS0',
'NRO_ACCES_CANAL3_MENOS1',
'NRO_ACCES_CANAL3_MENOS2',
'NRO_ACCES_CANAL3_MENOS3',
'NRO_ACCES_CANAL3_MENOS4',
'NRO_ACCES_CANAL3_MENOS5',
'NRO_ENTID_SSFF_MENOS0',
'NRO_ENTID_SSFF_MENOS1',
'NRO_ENTID_SSFF_MENOS2',
'NRO_ENTID_SSFF_MENOS3',
'NRO_ENTID_SSFF_MENOS4',
'NRO_ENTID_SSFF_MENOS5',
'FLG_SDO_OTSSFF_MENOS0',
'FLG_SDO_OTSSFF_MENOS1',
'FLG_SDO_OTSSFF_MENOS2',
'FLG_SDO_OTSSFF_MENOS3',
'FLG_SDO_OTSSFF_MENOS4',
'FLG_SDO_OTSSFF_MENOS5']
TABLA2 = data_ori.loc[list_ale, VARS_T2]
TABLA2.head()

,ID_CORRELATIVO,CODMES,SDO_ACTIVO_MENOS0,SDO_ACTIVO_MENOS1,SDO_ACTIVO_MENOS2,SDO_ACTIVO_MENOS3,SDO_ACTIVO_MENOS4,SDO_ACTIVO_MENOS5,FLG_SEGURO_MENOS0,FLG_SEGURO_MENOS1,...,NRO_ENTID_SSFF_MENOS2,NRO_ENTID_SSFF_MENOS3,NRO_ENTID_SSFF_MENOS4,NRO_ENTID_SSFF_MENOS5,FLG_SDO_OTSSFF_MENOS0,FLG_SDO_OTSSFF_MENOS1,FLG_SDO_OTSSFF_MENOS2,FLG_SDO_OTSSFF_MENOS3,FLG_SDO_OTSSFF_MENOS4,FLG_SDO_OTSSFF_MENOS5
20,11752,201208,0,0,0,0,0,0,0,0,...,2,2,2,2,1,1,1,1,1,1
22,98898,201208,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,82206,201208,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
28,50435,201208,0,0,0,0,0,0,1,1,...,5,5,4,4,1,1,1,1,1,1
31,79004,201208,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
TABLA2.to_csv('datos/churn/DS_Churn_Banca_INFO_HIST.csv',index=False)

In [49]:
data_ori['ATTRITION'].value_counts()/len(data_ori)

0    0.8454
1    0.1546
Name: ATTRITION, dtype: float64

In [50]:
TABLA1['ATTRITION'].value_counts()/len(TABLA1)

0    0.8447
1    0.1553
Name: ATTRITION, dtype: float64