In [1]:
#Carga de datos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data_1 = pd.read_csv('DS_Churn_Banca_INFO_HIST.csv', encoding= "ISO-8859-1", sep=",")
data_1.head()

,ID_CORRELATIVO,CODMES,SDO_ACTIVO_MENOS0,SDO_ACTIVO_MENOS1,SDO_ACTIVO_MENOS2,SDO_ACTIVO_MENOS3,SDO_ACTIVO_MENOS4,SDO_ACTIVO_MENOS5,FLG_SEGURO_MENOS0,FLG_SEGURO_MENOS1,...,NRO_ENTID_SSFF_MENOS2,NRO_ENTID_SSFF_MENOS3,NRO_ENTID_SSFF_MENOS4,NRO_ENTID_SSFF_MENOS5,FLG_SDO_OTSSFF_MENOS0,FLG_SDO_OTSSFF_MENOS1,FLG_SDO_OTSSFF_MENOS2,FLG_SDO_OTSSFF_MENOS3,FLG_SDO_OTSSFF_MENOS4,FLG_SDO_OTSSFF_MENOS5
0,11752,201208,0,0,0,0,0,0,0,0,...,2,2,2,2,1,1,1,1,1,1
1,98898,201208,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,82206,201208,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
3,50435,201208,0,0,0,0,0,0,1,1,...,5,5,4,4,1,1,1,1,1,1
4,79004,201208,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
data_1.head().T

                              0       1       2       3       4
ID_CORRELATIVO            11752   98898   82206   50435   79004
CODMES                   201208  201208  201208  201208  201208
SDO_ACTIVO_MENOS0             0       0       0       0       0
SDO_ACTIVO_MENOS1             0       0       0       0       0
SDO_ACTIVO_MENOS2             0       0       0       0       0
SDO_ACTIVO_MENOS3             0       0       0       0       0
SDO_ACTIVO_MENOS4             0       0       0       0       0
SDO_ACTIVO_MENOS5             0       0       0       0       0
FLG_SEGURO_MENOS0             0       0       0       1       0
FLG_SEGURO_MENOS1             0       0       0       1       0
FLG_SEGURO_MENOS2             0       0       0       0       0
FLG_SEGURO_MENOS3             0       0       0       0       0
FLG_SEGURO_MENOS4             0       0       0       0       0
FLG_SEGURO_MENOS5             0       0       0       0       0
NRO_ACCES_CANAL1_MENOS0       0       0       0       0       0
NRO_ACCES_CANAL1_MENOS1       0       0       0       0       0
NRO_ACCES_CANAL1_MENOS2       0       0       0       0       0
NRO_ACCES_CANAL1_MENOS3       0       0       0       0       2
NRO_ACCES_CANAL1_MENOS4       0       0       0       0       0
NRO_ACCES_CANAL1_MENOS5       0       0       0       0       0
NRO_ACCES_CANAL2_MENOS0       0       0       0       0       0
NRO_ACCES_CANAL2_MENOS1       0       0       0       0       0
NRO_ACCES_CANAL2_MENOS2       0       0       0       0       0
NRO_ACCES_CANAL2_MENOS3       0       0       0       0       0
NRO_ACCES_CANAL2_MENOS4       0       0       0       0       0
NRO_ACCES_CANAL2_MENOS5       0       0       0       0       0
NRO_ACCES_CANAL3_MENOS0       0       7      16       0       1
NRO_ACCES_CANAL3_MENOS1       0      11      19       0       0
NRO_ACCES_CANAL3_MENOS2       0       0       5       0       0
NRO_ACCES_CANAL3_MENOS3       0       0       8       0       1
NRO_ACCES_CANAL3_MENOS4       0       0       0       0       0
NRO_ACCES_CANAL3_MENOS5       0       0       0       0       0
NRO_ENTID_SSFF_MENOS0         2       0       1       5       0
NRO_ENTID_SSFF_MENOS1         2       0       1       6       0
NRO_ENTID_SSFF_MENOS2         2       0       1       5       0
NRO_ENTID_SSFF_MENOS3         2       0       1       5       0
NRO_ENTID_SSFF_MENOS4         2       0       1       4       0
NRO_ENTID_SSFF_MENOS5         2       0       1       4       0
FLG_SDO_OTSSFF_MENOS0         1       0       1       1       0
FLG_SDO_OTSSFF_MENOS1         1       0       1       1       0
FLG_SDO_OTSSFF_MENOS2         1       0       1       1       0
FLG_SDO_OTSSFF_MENOS3         1       0       1       1       0
FLG_SDO_OTSSFF_MENOS4         1       0       1       1       0
FLG_SDO_OTSSFF_MENOS5         1       0       1       1       0

In [3]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 44 columns):
ID_CORRELATIVO             10000 non-null int64
CODMES                     10000 non-null int64
SDO_ACTIVO_MENOS0          10000 non-null int64
SDO_ACTIVO_MENOS1          10000 non-null int64
SDO_ACTIVO_MENOS2          10000 non-null int64
SDO_ACTIVO_MENOS3          10000 non-null int64
SDO_ACTIVO_MENOS4          10000 non-null int64
SDO_ACTIVO_MENOS5          10000 non-null int64
FLG_SEGURO_MENOS0          10000 non-null int64
FLG_SEGURO_MENOS1          10000 non-null int64
FLG_SEGURO_MENOS2          10000 non-null int64
FLG_SEGURO_MENOS3          10000 non-null int64
FLG_SEGURO_MENOS4          10000 non-null int64
FLG_SEGURO_MENOS5          10000 non-null int64
NRO_ACCES_CANAL1_MENOS0    10000 non-null int64
NRO_ACCES_CANAL1_MENOS1    10000 non-null int64
NRO_ACCES_CANAL1_MENOS2    10000 non-null int64
NRO_ACCES_CANAL1_MENOS3    10000 non-null int64
NRO_ACCES_CANAL1_MENOS4    10000 non-null int64
NRO_ACCES_CANAL1_MENOS5    10000 non-null int64
NRO_ACCES_CANAL2_MENOS0    10000 non-null int64
NRO_ACCES_CANAL2_MENOS1    10000 non-null int64
NRO_ACCES_CANAL2_MENOS2    10000 non-null int64
NRO_ACCES_CANAL2_MENOS3    10000 non-null int64
NRO_ACCES_CANAL2_MENOS4    10000 non-null int64
NRO_ACCES_CANAL2_MENOS5    10000 non-null int64
NRO_ACCES_CANAL3_MENOS0    10000 non-null int64
NRO_ACCES_CANAL3_MENOS1    10000 non-null int64
NRO_ACCES_CANAL3_MENOS2    10000 non-null int64
NRO_ACCES_CANAL3_MENOS3    10000 non-null int64
NRO_ACCES_CANAL3_MENOS4    10000 non-null int64
NRO_ACCES_CANAL3_MENOS5    10000 non-null int64
NRO_ENTID_SSFF_MENOS0      10000 non-null int64
NRO_ENTID_SSFF_MENOS1      10000 non-null int64
NRO_ENTID_SSFF_MENOS2      10000 non-null int64
NRO_ENTID_SSFF_MENOS3      10000 non-null int64
NRO_ENTID_SSFF_MENOS4      10000 non-null int64
NRO_ENTID_SSFF_MENOS5      10000 non-null int64
FLG_SDO_OTSSFF_MENOS0      10000 non-null int64
FLG_SDO_OTSSFF_MENOS1      10000 non-null int64
FLG_SDO_OTSSFF_MENOS2      10000 non-null int64
FLG_SDO_OTSSFF_MENOS3      10000 non-null int64
FLG_SDO_OTSSFF_MENOS4      10000 non-null int64
FLG_SDO_OTSSFF_MENOS5      10000 non-null int64
dtypes: int64(44)
memory usage: 3.4 MB

In [4]:
data_1.describe(include='all')

,ID_CORRELATIVO,CODMES,SDO_ACTIVO_MENOS0,SDO_ACTIVO_MENOS1,SDO_ACTIVO_MENOS2,SDO_ACTIVO_MENOS3,SDO_ACTIVO_MENOS4,SDO_ACTIVO_MENOS5,FLG_SEGURO_MENOS0,FLG_SEGURO_MENOS1,...,NRO_ENTID_SSFF_MENOS2,NRO_ENTID_SSFF_MENOS3,NRO_ENTID_SSFF_MENOS4,NRO_ENTID_SSFF_MENOS5,FLG_SDO_OTSSFF_MENOS0,FLG_SDO_OTSSFF_MENOS1,FLG_SDO_OTSSFF_MENOS2,FLG_SDO_OTSSFF_MENOS3,FLG_SDO_OTSSFF_MENOS4,FLG_SDO_OTSSFF_MENOS5
count,10000.000000,10000.0,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,1.000000e+04,10000.000000,10000.000000,...,10000.000000,10000.0000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,50460.092400,201208.0,8.153705e+03,7.807822e+03,7.549552e+03,7.236627e+03,7.185591e+03,6.835872e+03,0.495700,0.459700,...,1.970500,1.9319,1.878600,1.860000,0.538400,0.536900,0.536600,0.535300,0.528400,0.525700
std,28980.502956,0.0,6.881066e+04,6.394435e+04,6.520424e+04,6.515622e+04,6.657661e+04,6.236148e+04,0.500007,0.498398,...,1.920208,1.9093,1.888708,1.874714,0.498548,0.498661,0.498684,0.498777,0.499218,0.499364
min,4.000000,201208.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25607.500000,201208.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,...,0.000000,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,50809.500000,201208.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,...,2.000000,2.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,75534.750000,201208.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,1.000000,...,3.000000,3.0000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,99989.000000,201208.0,3.275750e+06,2.399330e+06,2.748440e+06,2.761460e+06,2.780980e+06,2.426350e+06,1.000000,1.000000,...,10.000000,10.0000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
data_hist = data_1.copy()

In [15]:
data_hist[data_hist.columns.values[2:8]].mean(axis=1)

0            0.000000
1            0.000000
2            0.000000
3            0.000000
4            0.000000
5            0.000000
6            0.000000
7            0.000000
8         1446.666667
9            0.000000
10           0.000000
11        4028.333333
12      317320.000000
13        2911.666667
14           0.000000
15           0.000000
16           0.000000
17         966.666667
18           0.000000
19           0.000000
20           0.000000
21           0.000000
22       14466.666667
23           0.000000
24           0.000000
25        4088.333333
26           0.000000
27           0.000000
28           0.000000
29           0.000000
            ...
9970         0.000000
9971         0.000000
9972         0.000000
9973       498.333333
9974      1183.333333
9975       230.000000
9976         0.000000
9977         0.000000
9978         0.000000
9979      3506.666667
9980         0.000000
9981         0.000000
9982         0.000000
9983         0.000000
9984         0.000000
9985         0.000000
9986         0.000000
9987         0.000000
9988         0.000000
9989         0.000000
9990         0.000000
9991         0.000000
9992         0.000000
9993      2925.000000
9994      1738.333333
9995       131.666667
9996         0.000000
9997     46473.333333
9998       383.333333
9999         0.000000
Length: 10000, dtype: float64

,ID_CORRELATIVO,CODMES,SDO_ACTIVO_MENOS0,SDO_ACTIVO_MENOS1,SDO_ACTIVO_MENOS2,SDO_ACTIVO_MENOS3,SDO_ACTIVO_MENOS4,SDO_ACTIVO_MENOS5,FLG_SEGURO_MENOS0,FLG_SEGURO_MENOS1,...,NRO_ENTID_SSFF_MENOS2,NRO_ENTID_SSFF_MENOS3,NRO_ENTID_SSFF_MENOS4,NRO_ENTID_SSFF_MENOS5,FLG_SDO_OTSSFF_MENOS0,FLG_SDO_OTSSFF_MENOS1,FLG_SDO_OTSSFF_MENOS2,FLG_SDO_OTSSFF_MENOS3,FLG_SDO_OTSSFF_MENOS4,FLG_SDO_OTSSFF_MENOS5
0,11752,201208,0,0,0,0,0,0,0,0,...,2,2,2,2,1,1,1,1,1,1
1,98898,201208,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,82206,201208,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1
3,50435,201208,0,0,0,0,0,0,1,1,...,5,5,4,4,1,1,1,1,1,1
4,79004,201208,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
import matplotlib.pyplot as plt
data_1.columns

Index(['ID_CORRELATIVO', 'CODMES', 'SDO_ACTIVO_MENOS0', 'SDO_ACTIVO_MENOS1',
       'SDO_ACTIVO_MENOS2', 'SDO_ACTIVO_MENOS3', 'SDO_ACTIVO_MENOS4',
       'SDO_ACTIVO_MENOS5', 'FLG_SEGURO_MENOS0', 'FLG_SEGURO_MENOS1',
       'FLG_SEGURO_MENOS2', 'FLG_SEGURO_MENOS3', 'FLG_SEGURO_MENOS4',
       'FLG_SEGURO_MENOS5', 'NRO_ACCES_CANAL1_MENOS0',
       'NRO_ACCES_CANAL1_MENOS1', 'NRO_ACCES_CANAL1_MENOS2',
       'NRO_ACCES_CANAL1_MENOS3', 'NRO_ACCES_CANAL1_MENOS4',
       'NRO_ACCES_CANAL1_MENOS5', 'NRO_ACCES_CANAL2_MENOS0',
       'NRO_ACCES_CANAL2_MENOS1', 'NRO_ACCES_CANAL2_MENOS2',
       'NRO_ACCES_CANAL2_MENOS3', 'NRO_ACCES_CANAL2_MENOS4',
       'NRO_ACCES_CANAL2_MENOS5', 'NRO_ACCES_CANAL3_MENOS0',
       'NRO_ACCES_CANAL3_MENOS1', 'NRO_ACCES_CANAL3_MENOS2',
       'NRO_ACCES_CANAL3_MENOS3', 'NRO_ACCES_CANAL3_MENOS4',
       'NRO_ACCES_CANAL3_MENOS5', 'NRO_ENTID_SSFF_MENOS0',
       'NRO_ENTID_SSFF_MENOS1', 'NRO_ENTID_SSFF_MENOS2',
       'NRO_ENTID_SSFF_MENOS3', 'NRO_ENTID_SSFF_MENOS4',
       'NRO_ENTID_SSFF_MENOS5', 'FLG_SDO_OTSSFF_MENOS0',
       'FLG_SDO_OTSSFF_MENOS1', 'FLG_SDO_OTSSFF_MENOS2',
       'FLG_SDO_OTSSFF_MENOS3', 'FLG_SDO_OTSSFF_MENOS4',
       'FLG_SDO_OTSSFF_MENOS5'],
      dtype='object')